/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alf
 */
public class Imitador extends javax.swing.JFrame {

    /**
     * Creates new form Imitador
     */
    public Imitador() {
        initComponents();
        buttonGroup1.add(this.b_original1);
        buttonGroup1.add(this.b_original2);
        buttonGroup1.add(this.b_original3);

        buttonGroup2.add(this.b_espejo1);
        buttonGroup2.add(this.b_espejo2);
        buttonGroup2.add(this.b_espejo3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        b_original1 = new javax.swing.JRadioButton();
        b_original2 = new javax.swing.JRadioButton();
        b_original3 = new javax.swing.JRadioButton();
        b_original4 = new javax.swing.JCheckBox();
        b_original5 = new javax.swing.JCheckBox();
        b_original6 = new javax.swing.JCheckBox();
        txtOriginal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        spin_Original = new javax.swing.JSpinner();
        cmb_Original = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        b_espejo1 = new javax.swing.JRadioButton();
        b_espejo2 = new javax.swing.JRadioButton();
        b_espejo3 = new javax.swing.JRadioButton();
        b_espejo4 = new javax.swing.JCheckBox();
        b_espejo5 = new javax.swing.JCheckBox();
        b_espejo6 = new javax.swing.JCheckBox();
        txtEspejo = new javax.swing.JTextField();
        spin_Espejo = new javax.swing.JSpinner();
        cmb_Espejo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ORIGINAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        b_original1.setText("Opcion 1");
        b_original1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original1ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        b_original2.setText("Opcion 2");
        b_original2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original2ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        b_original3.setText("Opcion 3");
        b_original3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original3ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        b_original4.setText("Opcion 4");
        b_original4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original4ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        b_original5.setText("Opcion 5");
        b_original5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original5ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        b_original6.setText("Opcion 6");
        b_original6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_original6ActionPerformed(evt);
            }
        });
        getContentPane().add(b_original6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        txtOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOriginalActionPerformed(evt);
            }
        });
        txtOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOriginalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOriginalKeyTyped(evt);
            }
        });
        getContentPane().add(txtOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 150, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 490, -1));

        spin_Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_OriginalStateChanged(evt);
            }
        });
        getContentPane().add(spin_Original, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 150, -1));

        cmb_Original.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Original.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_OriginalItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_Original, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, -1));

        jLabel2.setText("ESPEJO");
        jLabel2.setEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        b_espejo1.setText("Opcion 1");
        b_espejo1.setEnabled(false);
        getContentPane().add(b_espejo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        b_espejo2.setText("Opcion 2");
        b_espejo2.setEnabled(false);
        getContentPane().add(b_espejo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        b_espejo3.setText("Opcion 3");
        b_espejo3.setEnabled(false);
        getContentPane().add(b_espejo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        b_espejo4.setText("Opcion 4");
        b_espejo4.setEnabled(false);
        getContentPane().add(b_espejo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        b_espejo5.setText("Opcion 5");
        b_espejo5.setEnabled(false);
        getContentPane().add(b_espejo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        b_espejo6.setText("Opcion 6");
        b_espejo6.setEnabled(false);
        getContentPane().add(b_espejo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        txtEspejo.setEnabled(false);
        getContentPane().add(txtEspejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 150, -1));

        spin_Espejo.setEnabled(false);
        getContentPane().add(spin_Espejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        cmb_Espejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Espejo.setEnabled(false);
        getContentPane().add(cmb_Espejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_original4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original4ActionPerformed
        this.b_espejo4.setSelected(this.b_original4.isSelected());
    }//GEN-LAST:event_b_original4ActionPerformed

    private void b_original1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original1ActionPerformed
        
        this.b_espejo1.setSelected(this.b_original1.isSelected());
    }//GEN-LAST:event_b_original1ActionPerformed

    private void b_original2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original2ActionPerformed
        this.b_espejo2.setSelected(this.b_original2.isSelected());
    }//GEN-LAST:event_b_original2ActionPerformed

    private void b_original3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original3ActionPerformed
        this.b_espejo3.setSelected(this.b_original3.isSelected());
    }//GEN-LAST:event_b_original3ActionPerformed

    private void b_original5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original5ActionPerformed
        this.b_espejo5.setSelected(this.b_original5.isSelected());
    }//GEN-LAST:event_b_original5ActionPerformed

    private void b_original6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_original6ActionPerformed
        this.b_espejo6.setSelected(this.b_original6.isSelected());
    }//GEN-LAST:event_b_original6ActionPerformed

    private void txtOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOriginalActionPerformed
        txtEspejo.setText(txtOriginal.getText());
    }//GEN-LAST:event_txtOriginalActionPerformed

    private void txtOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOriginalKeyTyped

    private void txtOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOriginalKeyPressed

    private void cmb_OriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_OriginalItemStateChanged
        this.cmb_Espejo.setSelectedIndex(this.cmb_Original.getSelectedIndex());
    }//GEN-LAST:event_cmb_OriginalItemStateChanged

    private void spin_OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_OriginalStateChanged
        this.spin_Espejo.setValue(this.spin_Original.getValue());
    }//GEN-LAST:event_spin_OriginalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b_espejo1;
    private javax.swing.JRadioButton b_espejo2;
    private javax.swing.JRadioButton b_espejo3;
    private javax.swing.JCheckBox b_espejo4;
    private javax.swing.JCheckBox b_espejo5;
    private javax.swing.JCheckBox b_espejo6;
    private javax.swing.JRadioButton b_original1;
    private javax.swing.JRadioButton b_original2;
    private javax.swing.JRadioButton b_original3;
    private javax.swing.JCheckBox b_original4;
    private javax.swing.JCheckBox b_original5;
    private javax.swing.JCheckBox b_original6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_Espejo;
    private javax.swing.JComboBox<String> cmb_Original;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spin_Espejo;
    private javax.swing.JSpinner spin_Original;
    private javax.swing.JTextField txtEspejo;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
