
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.DefaultEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alf
 */
public class Procesador_TxT extends javax.swing.JFrame {

    String ruta;
    String texto;

    public Procesador_TxT() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_txt = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_item_nuevo = new javax.swing.JMenuItem();
        menu_item_guardar = new javax.swing.JMenuItem();
        menu_item_abrir = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menu_item_cortar = new javax.swing.JMenuItem();
        menu_item_copiar = new javax.swing.JMenuItem();
        menu_item_pegar = new javax.swing.JMenuItem();
        menu_format = new javax.swing.JMenu();
        menu_fuente = new javax.swing.JMenu();
        menu_arial = new javax.swing.JMenu();
        menu_item_tam12 = new javax.swing.JRadioButtonMenuItem();
        menu_item_tam18 = new javax.swing.JMenuItem();
        menu_item_tam24 = new javax.swing.JMenuItem();
        menu_centaur = new javax.swing.JMenu();
        menu_item_centaur_12 = new javax.swing.JMenuItem();
        menu_item_centaur_18 = new javax.swing.JMenuItem();
        menu_item_centaur_24 = new javax.swing.JMenuItem();

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(panel_txt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 390));

        menu_archivo.setText("Archivo");

        menu_item_nuevo.setText("Nuevo");
        menu_item_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_nuevoActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_item_nuevo);

        menu_item_guardar.setText("Guardar");
        menu_item_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_item_guardar);

        menu_item_abrir.setText("Abrir");
        menu_item_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_abrirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_item_abrir);

        jMenuBar1.add(menu_archivo);

        menu_edit.setText("Edicion");

        menu_item_cortar.setText("Cortar");
        menu_item_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cortarActionPerformed(evt);
            }
        });
        menu_edit.add(menu_item_cortar);

        menu_item_copiar.setText("Copiar");
        menu_item_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_copiarActionPerformed(evt);
            }
        });
        menu_edit.add(menu_item_copiar);

        menu_item_pegar.setText("Pegar");
        menu_item_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_pegarActionPerformed(evt);
            }
        });
        menu_edit.add(menu_item_pegar);

        jMenuBar1.add(menu_edit);

        menu_format.setText("Formato");

        menu_fuente.setText("Fuente y Tamaño");

        menu_arial.setText("Arial");

        menu_item_tam12.setSelected(true);
        menu_item_tam12.setText("12");
        menu_item_tam12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_tam12ActionPerformed(evt);
            }
        });
        menu_arial.add(menu_item_tam12);

        menu_item_tam18.setText("18");
        menu_item_tam18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_tam18ActionPerformed(evt);
            }
        });
        menu_arial.add(menu_item_tam18);

        menu_item_tam24.setText("24");
        menu_item_tam24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_tam24ActionPerformed(evt);
            }
        });
        menu_arial.add(menu_item_tam24);

        menu_fuente.add(menu_arial);

        menu_centaur.setText("Centaur");

        menu_item_centaur_12.setText("12");
        menu_item_centaur_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_centaur_12ActionPerformed(evt);
            }
        });
        menu_centaur.add(menu_item_centaur_12);

        menu_item_centaur_18.setText("18");
        menu_item_centaur_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_centaur_18ActionPerformed(evt);
            }
        });
        menu_centaur.add(menu_item_centaur_18);

        menu_item_centaur_24.setText("24");
        menu_item_centaur_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_centaur_24ActionPerformed(evt);
            }
        });
        menu_centaur.add(menu_item_centaur_24);

        menu_fuente.add(menu_centaur);

        menu_format.add(menu_fuente);

        jMenuBar1.add(menu_format);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_pegarActionPerformed
        DefaultEditorKit.PasteAction pegar = new DefaultEditorKit.PasteAction();
        pegar.actionPerformed(evt);

    }//GEN-LAST:event_menu_item_pegarActionPerformed

    private void menu_item_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_nuevoActionPerformed
        this.panel_txt.setText("");
    }//GEN-LAST:event_menu_item_nuevoActionPerformed

    private void menu_item_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_abrirActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        try {
            BufferedReader br = new BufferedReader(new FileReader(ruta));
            try {
                texto = br.readLine();
                String linea;
                do {
                    linea = br.readLine();
                    if (linea != null) {
                        texto = texto + linea;
                    }
                } while (linea != null);
                this.panel_txt.setText(texto);
            } catch (IOException ex) {
                Logger.getLogger(Procesador_TxT.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Procesador_TxT.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menu_item_abrirActionPerformed

    private void menu_item_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_guardarActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        System.out.println(ruta);
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(ruta));
            texto = this.panel_txt.getText();
            bw.write(texto);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Procesador_TxT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_item_guardarActionPerformed

    private void menu_item_tam12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_tam12ActionPerformed
        Font arial_12 = new Font("Arial", Font.PLAIN, 12);
        this.panel_txt.setFont(arial_12);
    }//GEN-LAST:event_menu_item_tam12ActionPerformed

    private void menu_item_tam18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_tam18ActionPerformed
        Font arial_18 = new Font("Arial", Font.PLAIN, 18);
        this.panel_txt.setFont(arial_18);
    }//GEN-LAST:event_menu_item_tam18ActionPerformed

    private void menu_item_tam24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_tam24ActionPerformed
        Font arial_24 = new Font("Arial", Font.PLAIN, 24);
        this.panel_txt.setFont(arial_24);
    }//GEN-LAST:event_menu_item_tam24ActionPerformed

    private void menu_item_centaur_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_centaur_24ActionPerformed
        Font centaur_24 = new Font("Centaur", Font.PLAIN, 24);
        this.panel_txt.setFont(centaur_24);
    }//GEN-LAST:event_menu_item_centaur_24ActionPerformed

    private void menu_item_centaur_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_centaur_12ActionPerformed
        Font centaur_12 = new Font("Centaur", Font.PLAIN, 12);
        this.panel_txt.setFont(centaur_12);
    }//GEN-LAST:event_menu_item_centaur_12ActionPerformed

    private void menu_item_centaur_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_centaur_18ActionPerformed
        Font centaur_18 = new Font("Centaur", Font.PLAIN, 18);
        this.panel_txt.setFont(centaur_18);
    }//GEN-LAST:event_menu_item_centaur_18ActionPerformed

    private void menu_item_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cortarActionPerformed
        DefaultEditorKit.CutAction cortar = new DefaultEditorKit.CutAction();
        cortar.actionPerformed(evt);


    }//GEN-LAST:event_menu_item_cortarActionPerformed

    private void menu_item_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_copiarActionPerformed
        DefaultEditorKit.CopyAction copiar = new DefaultEditorKit.CopyAction();
        copiar.actionPerformed(evt);
    }//GEN-LAST:event_menu_item_copiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procesador_TxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procesador_TxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procesador_TxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procesador_TxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procesador_TxT().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_arial;
    private javax.swing.JMenu menu_centaur;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_format;
    private javax.swing.JMenu menu_fuente;
    private javax.swing.JMenuItem menu_item_abrir;
    private javax.swing.JMenuItem menu_item_centaur_12;
    private javax.swing.JMenuItem menu_item_centaur_18;
    private javax.swing.JMenuItem menu_item_centaur_24;
    private javax.swing.JMenuItem menu_item_copiar;
    private javax.swing.JMenuItem menu_item_cortar;
    private javax.swing.JMenuItem menu_item_guardar;
    private javax.swing.JMenuItem menu_item_nuevo;
    private javax.swing.JMenuItem menu_item_pegar;
    private javax.swing.JRadioButtonMenuItem menu_item_tam12;
    private javax.swing.JMenuItem menu_item_tam18;
    private javax.swing.JMenuItem menu_item_tam24;
    private javax.swing.JTextPane panel_txt;
    // End of variables declaration//GEN-END:variables
}
